// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9QNwnEgeYz1CTzcHTM0a-pZ8yzVigMTc',
    appId: '1:905646556994:web:87edb7651fa559aadb6adb',
    messagingSenderId: '905646556994',
    projectId: 'contact-sms-app',
    authDomain: 'contact-sms-app.firebaseapp.com',
    storageBucket: 'contact-sms-app.firebasestorage.app',
    measurementId: 'G-2Q6S3PFC63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4I1plGaBWbXNIIoG_NZ_HH0j9bsndO9Q',
    appId: '1:905646556994:android:549a71e1443c4244db6adb',
    messagingSenderId: '905646556994',
    projectId: 'contact-sms-app',
    storageBucket: 'contact-sms-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa9zfb8WC615-7NJWft36S14zUsWuHCvo',
    appId: '1:905646556994:ios:134948a9eaa3f283db6adb',
    messagingSenderId: '905646556994',
    projectId: 'contact-sms-app',
    storageBucket: 'contact-sms-app.firebasestorage.app',
    iosBundleId: 'com.example.contactSmsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa9zfb8WC615-7NJWft36S14zUsWuHCvo',
    appId: '1:905646556994:ios:134948a9eaa3f283db6adb',
    messagingSenderId: '905646556994',
    projectId: 'contact-sms-app',
    storageBucket: 'contact-sms-app.firebasestorage.app',
    iosBundleId: 'com.example.contactSmsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9QNwnEgeYz1CTzcHTM0a-pZ8yzVigMTc',
    appId: '1:905646556994:web:0b62dd505e0b2f53db6adb',
    messagingSenderId: '905646556994',
    projectId: 'contact-sms-app',
    authDomain: 'contact-sms-app.firebaseapp.com',
    storageBucket: 'contact-sms-app.firebasestorage.app',
    measurementId: 'G-W1K21DXHT4',
  );
}
